// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAndNWMojnqA-h5xAR8Lk2G_KXZToBOQzs',
    appId: '1:394559626532:web:9ce188edbcc2f46ceae7b1',
    messagingSenderId: '394559626532',
    projectId: 'chitchat-5a45f',
    authDomain: 'chitchat-5a45f.firebaseapp.com',
    databaseURL: 'https://chitchat-5a45f-default-rtdb.firebaseio.com',
    storageBucket: 'chitchat-5a45f.firebasestorage.app',
    measurementId: 'G-04KJCH0GTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf5xQzh55UPRjlhNvNqQf-9QOHlmBnVAM',
    appId: '1:394559626532:android:28e9a6c8b1e718f1eae7b1',
    messagingSenderId: '394559626532',
    projectId: 'chitchat-5a45f',
    databaseURL: 'https://chitchat-5a45f-default-rtdb.firebaseio.com',
    storageBucket: 'chitchat-5a45f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2FJgr9JXuQPS_Z7Ixf0yINAnEdcZwTOI',
    appId: '1:394559626532:ios:8c7df4292c00a289eae7b1',
    messagingSenderId: '394559626532',
    projectId: 'chitchat-5a45f',
    databaseURL: 'https://chitchat-5a45f-default-rtdb.firebaseio.com',
    storageBucket: 'chitchat-5a45f.firebasestorage.app',
    androidClientId: '394559626532-g3ctenrjtuks1nieo14do30gohdbejug.apps.googleusercontent.com',
    iosClientId: '394559626532-ou8etbcfkcicst60vj7k34nssoaukerf.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappProject',
  );
}
