// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2maNV8EqljgdQ3vop2F0BLRO1GGPUNj0',
    appId: '1:619779037573:web:63a532a1123f7af73c4cec',
    messagingSenderId: '619779037573',
    projectId: 'chit-chat-ed913',
    authDomain: 'chit-chat-ed913.firebaseapp.com',
    databaseURL: 'https://chit-chat-ed913-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-ed913.firebasestorage.app',
    measurementId: 'G-2MFQDB5119',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGRbL0amVNAyNp6uaTu_6e1UV23227gA',
    appId: '1:619779037573:android:5958e9567a1a0dbe3c4cec',
    messagingSenderId: '619779037573',
    projectId: 'chit-chat-ed913',
    databaseURL: 'https://chit-chat-ed913-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-ed913.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37-49myVs88tZVHlzpT34ytHFDf3Kvy8',
    appId: '1:619779037573:ios:c40b0c00991611813c4cec',
    messagingSenderId: '619779037573',
    projectId: 'chit-chat-ed913',
    databaseURL: 'https://chit-chat-ed913-default-rtdb.firebaseio.com',
    storageBucket: 'chit-chat-ed913.firebasestorage.app',
    iosClientId: '619779037573-sgtsh5v3n521jgvnqjvd5kkoenvi9b1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappProject',
  );
}
